name: hello-pusher
on:
  push:
    branches:
    - master
jobs:
  greet:
    name: Greet to pusher
    runs-on: ubuntu-latest
    outputs:
      greet_text: ${{ steps.print_greet.outputs.text}}
    steps:
    - id: print_greet
      name: Print a greeting
      run: echo "::set-output name=text::hello pusher!!"
    timeout-minutes: 1
